/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YieldPredictRouteImport } from './routes/yield-predict'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiseaseRouteImport } from './routes/disease'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CropsRouteImport } from './routes/crops'
import { Route as CropRecommendRouteImport } from './routes/crop-recommend'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'

const YieldPredictRoute = YieldPredictRouteImport.update({
  id: '/yield-predict',
  path: '/yield-predict',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseaseRoute = DiseaseRouteImport.update({
  id: '/disease',
  path: '/disease',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsRoute = CropsRouteImport.update({
  id: '/crops',
  path: '/crops',
  getParentRoute: () => rootRouteImport,
} as any)
const CropRecommendRoute = CropRecommendRouteImport.update({
  id: '/crop-recommend',
  path: '/crop-recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/crop-recommend': typeof CropRecommendRoute
  '/crops': typeof CropsRoute
  '/dashboard': typeof DashboardRoute
  '/disease': typeof DiseaseRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/schemes': typeof SchemesRoute
  '/signup': typeof SignupRoute
  '/yield-predict': typeof YieldPredictRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/crop-recommend': typeof CropRecommendRoute
  '/crops': typeof CropsRoute
  '/dashboard': typeof DashboardRoute
  '/disease': typeof DiseaseRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/schemes': typeof SchemesRoute
  '/signup': typeof SignupRoute
  '/yield-predict': typeof YieldPredictRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/crop-recommend': typeof CropRecommendRoute
  '/crops': typeof CropsRoute
  '/dashboard': typeof DashboardRoute
  '/disease': typeof DiseaseRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/schemes': typeof SchemesRoute
  '/signup': typeof SignupRoute
  '/yield-predict': typeof YieldPredictRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/crop-recommend'
    | '/crops'
    | '/dashboard'
    | '/disease'
    | '/login'
    | '/marketplace'
    | '/schemes'
    | '/signup'
    | '/yield-predict'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/crop-recommend'
    | '/crops'
    | '/dashboard'
    | '/disease'
    | '/login'
    | '/marketplace'
    | '/schemes'
    | '/signup'
    | '/yield-predict'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/crop-recommend'
    | '/crops'
    | '/dashboard'
    | '/disease'
    | '/login'
    | '/marketplace'
    | '/schemes'
    | '/signup'
    | '/yield-predict'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  CropRecommendRoute: typeof CropRecommendRoute
  CropsRoute: typeof CropsRoute
  DashboardRoute: typeof DashboardRoute
  DiseaseRoute: typeof DiseaseRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  SchemesRoute: typeof SchemesRoute
  SignupRoute: typeof SignupRoute
  YieldPredictRoute: typeof YieldPredictRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yield-predict': {
      id: '/yield-predict'
      path: '/yield-predict'
      fullPath: '/yield-predict'
      preLoaderRoute: typeof YieldPredictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disease': {
      id: '/disease'
      path: '/disease'
      fullPath: '/disease'
      preLoaderRoute: typeof DiseaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops': {
      id: '/crops'
      path: '/crops'
      fullPath: '/crops'
      preLoaderRoute: typeof CropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-recommend': {
      id: '/crop-recommend'
      path: '/crop-recommend'
      fullPath: '/crop-recommend'
      preLoaderRoute: typeof CropRecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  CropRecommendRoute: CropRecommendRoute,
  CropsRoute: CropsRoute,
  DashboardRoute: DashboardRoute,
  DiseaseRoute: DiseaseRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  SchemesRoute: SchemesRoute,
  SignupRoute: SignupRoute,
  YieldPredictRoute: YieldPredictRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
